import { useCallback, useState } from 'react';
import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { Button } from '@/components/ui/Button';
import type { AnalysisResult } from '@/lib/types';
import { TUMOR_CLASS_LABELS } from '@/lib/types';
import { formatConfidence, formatTimestamp } from '@/lib/utils';

interface ReportButtonProps {
  result: AnalysisResult;
}

export function ReportButton({ result }: ReportButtonProps) {
  const [generating, setGenerating] = useState(false);

  const generateReport = useCallback(async () => {
    setGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Header
      doc.setFillColor(56, 29, 42); // secondary color
      doc.rect(0, 0, pageWidth, 40, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('Neuromed', 20, 20);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('AI-Powered Brain Tumor Detection Report', 20, 30);

      // Report info
      doc.setTextColor(13, 13, 13);
      let y = 55;

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Analysis Summary', 20, y);
      y += 12;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');

      const lines: [string, string][] = [
        ['Report ID:', result.id],
        ['Timestamp:', formatTimestamp(result.timestamp)],
        ['Processing Time:', `${result.processingTimeMs}ms`],
        ['', ''],
        ['CLASSIFICATION', ''],
        ['Predicted Class:', TUMOR_CLASS_LABELS[result.predictedClass]],
        [
          'Primary Confidence:',
          formatConfidence(
            result.confidenceScores.find(
              (s) => s.tumorClass === result.predictedClass,
            )?.confidence ?? 0,
          ),
        ],
      ];

      for (const [label, value] of lines) {
        if (label === '') {
          y += 6;
          continue;
        }
        if (value === '') {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(11);
          doc.text(label, 20, y);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(10);
          y += 10;
          continue;
        }
        doc.setFont('helvetica', 'bold');
        doc.text(label, 20, y);
        doc.setFont('helvetica', 'normal');
        doc.text(value, 80, y);
        y += 8;
      }

      // Confidence breakdown
      y += 8;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Confidence Distribution', 20, y);
      y += 10;

      doc.setFontSize(10);
      const sortedScores = [...result.confidenceScores].sort(
        (a, b) => b.confidence - a.confidence,
      );

      for (const score of sortedScores) {
        const label = TUMOR_CLASS_LABELS[score.tumorClass];
        const conf = formatConfidence(score.confidence);
        const barWidth = score.confidence * 100;

        doc.setFont('helvetica', 'normal');
        doc.text(label, 20, y);
        doc.text(conf, 160, y, { align: 'right' });

        // Bar
        doc.setFillColor(229, 225, 219);
        doc.roundedRect(20, y + 2, 140, 4, 2, 2, 'F');
        doc.setFillColor(255, 80, 24);
        doc.roundedRect(20, y + 2, barWidth * 1.4, 4, 2, 2, 'F');

        y += 14;
      }

      // Disclaimer
      y += 10;
      doc.setFillColor(250, 248, 244);
      doc.roundedRect(15, y - 4, pageWidth - 30, 30, 3, 3, 'F');
      doc.setFontSize(8);
      doc.setTextColor(90, 85, 81);
      doc.text(
        'DISCLAIMER: This report is generated by Neuromed, a clinical decision support tool.',
        20,
        y + 2,
      );
      doc.text(
        'It does not replace professional medical diagnosis. All results should be reviewed',
        20,
        y + 10,
      );
      doc.text(
        'and validated by a licensed physician before any clinical decisions are made.',
        20,
        y + 18,
      );

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by Neuromed | ${new Date().toISOString()}`,
        pageWidth / 2,
        285,
        { align: 'center' },
      );

      doc.save(`neuromed-report-${result.id.slice(0, 8)}.pdf`);
    } finally {
      setGenerating(false);
    }
  }, [result]);

  return (
    <Button
      variant="secondary"
      size="sm"
      onClick={generateReport}
      loading={generating}
    >
      <Download className="h-4 w-4" aria-hidden="true" />
      Download Report
    </Button>
  );
}
